version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mc-frontend-controller-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-179h0fq7xrftd"
s3_prefix = "mc-frontend-controller-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
